### ISSUE TITLE
Please reconsider CurseForge third-party distribution setting

### ISSUE THREAD

**Issue by copygirl** [Alpvax/GoProne#12]
Apologies for the lack of a personalized message, but I will be contacting a number of modders today.
Your mod, GoProne, is one of the few that can't be downloaded by third-party launchers and other tools.
With the following GitHub Gist I would like to try changing your mind, and those of other creators.

https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

Thank you for your work! :green_heart:

**Comment by Alpvax** [comment]
Done!
The main reason I had 3rd party access disabled was due to an oversight, I desired to prevent rehosting rather than restricting alternative launchers. Also the rewards don't hurt 😂
I would prefer that there was incentive for curseforge to improve their site, and I agree that the current state of both the site and the launcher are horrendous from both player and modder points of view.
Your tool looks good, I will probably use it next time I'm putting together a pack for me and a few friends to play, especially as we tend to play on linux!

**Comment by copygirl** [comment]
Thank you for changing this!

A couple more points:
- The setting doesn't prevent re-hosting, in fact it encourages it. Anyone can download mods from CurseForge regardless and upload them elsewhere. The only thing it does is limit launchers and other tools from using CurseForge's official way of aquiring mods through their API. Meanwhile, those avoiding the API can avoid the restriction. It's all a bit of a mess.
- An alternative for hosting mods to consider is [Modrinth](https://modrinth.com/). It comes with some very important usability improvements when compared to CurseForge. They're also working on ways to pay back creators hosting their mods there. It's already seeing some adoption from bigger modders.
- Just a quick note that packwiz (or any of the others tools I mentioned) are not made by me nor have I contributed to any of them, in case it was unclear. But packwiz is a nice tool that can be used to manage mods, check for updates, and its format is very git-friendly, if you want to keep track of changes that way. (Organization and cooperation is easier this way than just handling .jar files or so.)
