### ISSUE TITLE
Does not work with certain other mods installed

### ISSUE THREAD

**Issue by Alpvax** [Alpvax/GoProne#3]
> Quote from VL4DST3R >> ([from CurseForge](https://www.curseforge.com/minecraft/mc-mods/goprone?comment=28))
>  Your mod no longer works when installed next to either Torch Optimizer or Light Level Overlay Reloaded.

> Quote from VL4DST3R >> ([from CurseForge](https://www.curseforge.com/minecraft/mc-mods/goprone?comment=31))
>  Actually again, now i tested it together with another mod: Xaero's Minimap and again, the same thing happened. Your mod is definitely loaded, even shows up in the controls menu, it's just that the key does nothing. There is no keybind conflict, and i even tried changing it around to double check and no, the same issue persists. Yes, i do have other mods with keybinds, for example "Shoulder Surfing" and "FPS Reducer", not to mention Optifine itself to name a few. I wanted to suggest maybe it's a number of mods loaded kind of issue, but i did add other mods that didn't trigger this issue.

I require a mod list so I can debug the issue further. I need the mods installed and their versions, as well as your Forge version. If you know how to find your log file that would be useful too.

**Comment by VL4DST3R** [comment]
Before addressing your requests i noticed another interesting thing yesterday while playing with some friends: in multiplayer it seems to work as intended (with mods like xaeros minimap installed), it's only in SP the go prone mod stops working.

To reiterate, so far i found your mod to stop working* when paired together with:
- Torch Optimizer
- Light Level Overlay Reloaded
- Xaeros Minimap

(*) not consistently, sometimes it just works, see below.

EDIT: Scratch that! i just restarted my game to get a more concise log file to send you and now for some inexplicable reason the go prone works. Even after multiple restarts. I haven't changed any setting, nor removed or added any mods.

EDIT2: Ok, this is definitely inconsistent, the mod sometimes works, sometimes doesn't, and SOMETIMES even causes another mod to crash entirely (more info about this particular case at the bottom). I think it's the way forge loads mods at startup that's causing all this, not your mod in particular.


Now, for the requested info:

- Latest log where the issue is still present, but i found no mentions of go prone other than the normal forge initialization stuff: https://pastebin.com/pfuFW5Dz

- Forge version is 28.0.45 (at the time latest and only version that supports optifine, which is also installed)

- Currently installed mods:
```
betteranimals-1.14.4-5.2.1.jar
BetterAnimationsCollection2-v1.1b3-1.14.4.jar
CleanView-1.14.4-v1.jar
FastLeafDecay-v17.jar
Fence+Jumper-1.14.4-1.0.8.jar
followingvillagers-1.14.4-1.2.0.jar
FpsReducer-mc1.14.4-1.12.5.jar
FreeLook-1.14.4-1.3.jar
goprone-1.14.x-1.0.3.jar
lenientcreepers-1.14.x-v1.0.1.jar
LetMeSleep-v1.0-1.14.3.jar
OptiFine_1.14.4_HD_U_F4_pre2.jar
ShoulderSurfing-1.14.4-1.19.jar
smooth-scrolling-everywhere-1.0.jar
sneakthroughberries-1.14.4-1.1.1-forge.jar
swingthroughgrass-1.14.4-1.3.2.jar
thirdpersonelytra-1.14.4v1.2.jar
torchoptimizer-1.14.4-2.1.6.jar
Xaeros_Minimap_1.17.7_Forge_1.14.4.jar
```


As mentioned above, I managed to pull off an even weirder thing: after loading a map, sometimes if i press the go prone key (currently set to ALT) it completely crashes the game. The log that resulted when this happened provided here: https://pastebin.com/kaC9qkz1. From the log it seems to be caused by the torch optimizer mod, but the thing is, if i don't press anything right at startup i haven't ever seen it crash, so the fact it did when pressing the key for go prone leads me to believe it is affected by it somehow.

I'm sorry to provide such a disjointed bug report, but i am as confused as you probably are after  reading all this. If i can help in any way with sorting this out let me know.

**Comment by Alpvax** [comment]
Thanks for the detailed info, I will look into the issue as soon as I get a chance

**Comment by VL4DST3R** [comment]
It seems a lot of mods have issues with the latest Optifine-Forge compatibility, see [here ](https://github.com/mezz/JustEnoughItems/issues/1668)and [here](https://github.com/sp614x/optifine/issues/2737). So again, i lean towards this not being your fault or something fixable on your side, they need to sort this stuff out, and all we can do is wait...

**Comment by Alpvax** [comment]
My first assumption when you mentioned you had optifine installed was that that was what it was. Could you try without my mod and see if you can still get the crash? And maybe try without optifine?

**Comment by sp614x** [comment]
OptiFine 1.14.4_HD_U_F4_pre3
 - fixed Forge access transformers (#2737)

**Comment by Curros** [comment]
With the Optifine version:
- preview_OptiFine_1.15.2_HD_U_G1_pre16.jar
- goprone-1.15.x-1.3.0.jar

Does a weird zoom, so not working correctly.

**Comment by Alpvax** [comment]
The zoom happens normally, due to the change in speed (it will happen even without my mod). I will look into issues with optifine when I get a chance

**Comment by Curros** [comment]
> 
> 
> The zoom happens normally, due to the change in speed (it will happen even without my mod). I will look into issues with optifine when I get a chance

That's strange, if I deactivate optifine I don't the zoom doesn't happen, but god to know that you will see it! :D
Thanks!

**Comment by Alpvax** [comment]
There is a small zoom effect. Maybe optifine amplifies it

**Comment by Curros** [comment]
OMG the shame!
After seeing your comment I wonder if OptiFine has a zoom effect, and that's it, a Zoom effect mapped to the same key.
So sorry!
Now is working perfect!
- preview_OptiFine_1.15.2_HD_U_G1_pre16.jar
- goprone-1.15.x-1.3.0.jar
